[project]
name = "voicer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "edge-tts>=7.2.3",
    "streamlit>=1.51.0",
]
